# mocap fixed frame is almost coincide with earch NED frame.

end_effector_name: tail_ball
end_effector_dist: 0 # 0.43 from link4

#deprecated, move to first_contact_point: contact_point_height: 0.785 # consider the bend: 0.8 => 0.785
first_contact_point: [0.08, 0.25, 0.785] # y = 0.3: real machine exceed
first_contact_normal: [0, 0, -1]
contact_reaction_force: 4.5 # norm [N], combined with first constact norml
move_friction_force: 3.5 # norm [N]

# about the openning planning after moving cover
cover_thickness: 0.04 # [m], true is 0.05, but we have to consider the bend of the misumi frame (0.8 -> 0.78)
squeeze_center_offset_x: 0.0 # [m], since we can not move the cover completly, have to add offset
squeeze_center_offset_y: 0.0 # [m], should be 0.05, but the control offset is big. since we can not move the cover completly, have to add offset

# phase1:
approach_trajectory_period: 5.0
contact_offset: [0, 0, -0.05]

# phase2:
contact_dist_err_thresh: 0.02

# phase3:
move_trajectory_period: 9.0
move_end_point: [0.08, -0.3, 0.785]

# phase4:
reset_pose_period: 5.0
reset_end_effector_point: [0, 0, 0.3]

end_effector:
  # inverse kinematics
  differential_kinematics_count: 200
  motion_func_rate: 0

  # cost
  differential_kinematics_cost:
    cartesian_constraint:
      verbose: true
      w_pos_err_constraint: 1.0
      w_att_err_constraint: 1.0 #1.0
    state_vel:
      verbose: true
      w_joint_vel: 0.001
      w_root_translational_vel: 0.001 #0.001 #0.005
      w_root_rotational_vel: 0.001 #0.001 #0.005

  # constraint
  differential_kinematics_constraint:
    state_limit:
      verbose: true
      joint_vel_thre: 0.1 #0.17 , 0.02 is not valid for full_body
      root_translational_vel_thre: 1 #0.1
      root_rotational_vel_thre: 1 #0.1
      joint_vel_constraint_range: 0.11
      joint_vel_forbidden_range: 0.02
      vebose: true
    stability:
      verbose: true
    collision_avoidance:
      verbose: true
      collision_distance_constraint_range: 0.08 #0.05
      collision_distance_forbidden_range: 0.05 #0.02
    cog_motion:
      verbose: true
      cog_omega_limit_flag: false
      cog_velocity_limit: [0.05, 0.05, 0.01]  # [x,y,z] (m) in world frame
      cog_angular_limit: [0.05, 0.05, 0.05]  # [x,y,z] (rad) in world frame
